### ISSUE TITLE
where to put the "guns plugin" - skintextures?

### ISSUE THREAD

**Issue by RonXTCdaBass** [commaster101/classicube-thingys#1]
### Hello and THX for sharing your Plugins!!

i have installed your _Guns Plugin_ but don´t know where should i put the textures for the weapons? 
i think users wanna see the guns in the itemlist.

and 2. since i´ve installed the _Swim cs_, i have a courious bug ...
every time i click something in the itemlist, changes the _breakable liquids_ ...

![breakable_bug_01](https://github.com/commaster101/classicube-thingys/assets/115949021/a7a73c32-d537-40fa-9c20-3a0fb2e88789)

**Comment by commaster101** [comment]
Sorry about the wait. To make a gun show up in the inventory just texture the block corresponding to it (you my need to change the draw property as well). As for the bug with swimming I can't find anything, if you could give more information on how to recreate it that could be helpful.
